repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: env FORCE_COLOR=1 ruff format --check
        args:
          - --quiet
        language: system
        types: [ python ]
        stages: [ pre-commit ]
      - id: lint
        name: lint
        entry: env FORCE_COLOR=1 ruff check
        args:
          - --output-format=concise
          - --quiet
        language: system
        types: [ python ]
        stages: [ pre-commit ]
      - id: type-check
        name: type-check
        entry: env FORCE_COLOR=1 ty check
        args:
          - --output-format=concise
          - --error-on-warning
        language: system
        types: [ python ]
        stages: [ pre-commit ]